### ISSUE TITLE
Atom 1.17 : Failed to activate the tree-view-auto-fold package

### ISSUE THREAD

**Issue by NTShop** [NutterV/atom-tree-view-auto-fold#1]
Upon install and trying to activate I see this in Atom 1.17: 

Failed to activate the tree-view-auto-fold package
Cannot read property 'includes' of undefined

TypeError: Cannot read property 'includes' of undefined
  at Object.allPathSegments (/home/admin/.atom/packages/tree-view-auto-fold/lib/utils.coffee:18:19)
  at TreeViewUI.module.exports.TreeViewUI.addFileSegmentsToExceptions (/home/admin/.atom/packages/tree-view-auto-fold/lib/treeviewui.coffee:152:5)
  at TreeViewUI.module.exports.TreeViewUI.populateFilterEntries (/home/admin/.atom/packages/tree-view-auto-fold/lib/treeviewui.coffee:146:10)
  at TreeViewUI.module.exports.TreeViewUI.updateRoots (/home/admin/.atom/packages/tree-view-auto-fold/lib/treeviewui.coffee:236:6)
  at /home/admin/.atom/packages/tree-view-auto-fold/lib/treeviewui.coffee:122:12
  at Config.module.exports.Config.observeKeyPath (<embedded>:17779:13)
  at Config.module.exports.Config.observe (<embedded>:17304:27)
  at TreeViewUI.module.exports.TreeViewUI.subscribeUpdateConfigurations (/home/admin/.atom/packages/tree-view-auto-fold/lib/treeviewui.coffee:118:19)
  at new TreeViewUI (/home/admin/.atom/packages/tree-view-auto-fold/lib/treeviewui.coffee:35:6)
  at Object.toggle (/home/admin/.atom/packages/tree-view-auto-fold/lib/main.coffee:90:25)
  at Object.doInitPackage (/home/admin/.atom/packages/tree-view-auto-fold/lib/main.coffee:83:6)
  at Object.activate (/home/admin/.atom/packages/tree-view-auto-fold/lib/main.coffee:67:6)
  at Package.module.exports.Package.activateNow (<embedded>:68263:25)
  at <embedded>:68235:38
  at Package.module.exports.Package.measure (<embedded>:68109:21)
  at <embedded>:68228:32
  at Package.module.exports.Package.activate (<embedded>:68225:40)
  at PackageManager.module.exports.PackageManager.activatePackage (<embedded>:20426:40)
  at <embedded>:52634:35
  at exit (<embedded>:52243:22)
  at triggerExitCallback (<embedded>:108335:17)
  at <embedded>:108356:17
  at Socket.<anonymous> (<embedded>:108217:15)
  at emitOne (events.js:101:20)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:493:12)
The error was thrown from the tree-view-auto-fold package.

**Comment by NutterV** [comment]
I believe I've fixed this issue, I've published an update, would you mind retrying?
